baseURL = 'https://hayatehay.github.io/'
languageCode = 'ja'
languageName = 'Japanese'
defaultContentLanguage = 'ja'
hasCJKLanguage = true
title = '麻浪迅のホームページ'
theme = 'coder'
copyright = '(C) 2023-2024 Jin ASA-NAMI'

[markup.goldmark.renderer]
unsafe = true

[params]
author = 'Jin Asanami'
info = ["麻浪迅のホームページにようこそ！"]
favicon = '/images/common/logo.png'
avatarURL = '/images/common/logo.png'
colorScheme = "auto"
hideColorSchemeToggle = true
dateFormat = "2006-01-02"
since = 2022

[[menu.main]]
name = "NEWS"
weight = 1
url = "news/"

[[menu.main]]
name = "BIO"
weight = 2
url = "bio/"

[[menu.main]]
name = "MUSIC"
weight = 3
url = "music/"

[[menu.main]]
name = "BLOG"
weight = 4
url = "blog/"

[[menu.main]]
name = "WORKS"
weight = 5
url = "works/"

[[menu.main]]
name = "EVENT"
weight = 6
url = "event/"

[[menu.main]]
name = "LINK"
weight = 7
url = "link/"

[[menu.main]]
name = "CONTACT"
weight = 8
url = "contact/"
