baseURL = 'https://hayatehay.github.io/'
languageCode = 'ja'
languageName = 'Japanese'
defaultContentLanguage = 'ja'
hasCJKLanguage = true
title = '麻浪迅のホームページ'
theme = 'coder'
copyright = '(C) 2023-2024 Jin ASA-NAMI'

[markup.goldmark.renderer]
unsafe = true

[params]
author = 'Jin Asanami'
info = ["麻浪迅のホームページにようこそ！"]
favicon_32 = '/img/logo32.png'
favicon_16 = '/img/logo16.png'
avatarURL = '/img/logo.png'
colorScheme = "auto"
hideColorSchemeToggle = true
dateFormat = "2006-01-02"
since = 2022
custom_css = ["/css/icons.css"]

[[params.social]]
  name = "9ineverse.com"
  weight = 1
  url = "https://9ineverse.com/@hayatehay"

[[params.social]]
  name = "Misskey.io"
  weight = 1
  url = "https://misskey.io/@hayatehay"

[[params.social]]
  name = "Misskey.design"
  weight = 3
  url = "https://misskey.design/@hayatehay"

[[params.social]]
  name = "Soundcloud"
  weight = 4
  url = "https://soundcloud.com/hayatehay"

[[params.social]]
  name = "Skeb"
  weight = 5
  url = "https://skeb.jp/@hayatehay"

[menu]
[[menu.main]]
name = "NEWS"
weight = 1
url = "news/"

[[menu.main]]
name = "BIO"
weight = 2
url = "bio/"

[[menu.main]]
name = "MUSIC"
weight = 3
url = "music/"

[[menu.main]]
name = "WORKS"
weight = 4
url = "works/"

[[menu.main]]
name = "SAMPLE"
weight = 5
url = "sample/"

[[menu.main]]
name = "EVENT"
weight = 6
url = "event/"

[[menu.main]]
name = "BLOG"
weight = 7
url = "blog/"

[[menu.main]]
name = "LINK"
weight = 8
url = "link/"

[[menu.main]]
name = "CONTACT"
weight = 9
url = "contact/"

